/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/captures": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Capture something into the pool
         * @description The body is a capture envelope. Submitting the same capture twice has no additional effect and answers 200 rather than 201.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CaptureEnvelope"];
                };
            };
            responses: {
                /** @description Already captured. `matchedOn` says which identity the replay matched. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CaptureOutcome"];
                    };
                };
                /** @description Captured. `Location` names the item. */
                201: {
                    headers: {
                        Location: string;
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CaptureOutcome"];
                    };
                };
                /** @description The body could not be read as an envelope. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description The refusal's kind, with its facts beside it. */
                            error: {
                                /** @enum {string} */
                                code: "malformed-json" | "malformed-envelope";
                            } & {
                                [key: string]: unknown;
                            };
                        };
                    };
                };
                /** @description The identity exists and the content differs. Nothing was written. */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description The refusal's kind, with its facts beside it. */
                            error: {
                                /** @enum {string} */
                                code: "capture-id-conflict" | "source-item-changed";
                            } & {
                                [key: string]: unknown;
                            };
                        };
                    };
                };
                /** @description The body was not JSON. */
                415: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description The refusal's kind, with its facts beside it. */
                            error: {
                                /** @enum {string} */
                                code: "unsupported-media-type";
                            } & {
                                [key: string]: unknown;
                            };
                        };
                    };
                };
                /** @description The envelope was understood and the pool declined it. */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description The refusal's kind, with its facts beside it. */
                            error: {
                                /** @enum {string} */
                                code: "unknown-payload-type" | "payload-invalid" | "missing-asset-slot" | "unknown-asset";
                            } & {
                                [key: string]: unknown;
                            };
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/feed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read the feed
         * @description Every item chronologically by capture time, including archived and superseded ones. Follow `next` until it is absent.
         */
        get: {
            parameters: {
                query?: {
                    /** @description `newest-first` (default) or `oldest-first`. */
                    order?: string;
                    /** @description 1–500. Defaults to 50. A larger value is refused, not clamped. */
                    limit?: string;
                    /** @description The position to continue from: `<at>,<id>`, or a bare instant as a coarse entry point. */
                    after?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description A page of the feed. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ItemSlice"];
                    };
                };
                /** @description A parameter was understood and refused. */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description The refusal's kind, with its facts beside it. */
                            error: {
                                /** @enum {string} */
                                code: "limit-too-large" | "bad-limit" | "bad-order" | "bad-position";
                            } & {
                                [key: string]: unknown;
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/queue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read the queue
         * @description Every item that is unprocessed, unarchived and not superseded, oldest first by default. Paginated by a **content-time** position, which is spelled like the feed's and means something else: the two are not interchangeable.
         */
        get: {
            parameters: {
                query?: {
                    /** @description `oldest-first` (default) or `newest-first`. */
                    order?: string;
                    /** @description 1–500. Defaults to 50. A larger value is refused, not clamped. */
                    limit?: string;
                    /** @description The position to continue from: `<at>,<id>`, or a bare instant as a coarse entry point. */
                    after?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description A page of the queue. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ItemSlice"];
                    };
                };
                /** @description A parameter was understood and refused. */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description The refusal's kind, with its facts beside it. */
                            error: {
                                /** @enum {string} */
                                code: "limit-too-large" | "bad-limit" | "bad-order" | "bad-position";
                            } & {
                                [key: string]: unknown;
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/archived": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read the archive
         * @description Every archived item, on the queue's key and default. Archiving hides an item from the queue; it stays in the feed and stays processable.
         */
        get: {
            parameters: {
                query?: {
                    /** @description `oldest-first` (default) or `newest-first`. */
                    order?: string;
                    /** @description 1–500. Defaults to 50. A larger value is refused, not clamped. */
                    limit?: string;
                    /** @description The position to continue from: `<at>,<id>`, or a bare instant as a coarse entry point. */
                    after?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description A page of the archive. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ItemSlice"];
                    };
                };
                /** @description A parameter was understood and refused. */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description The refusal's kind, with its facts beside it. */
                            error: {
                                /** @enum {string} */
                                code: "limit-too-large" | "bad-limit" | "bad-order" | "bad-position";
                            } & {
                                [key: string]: unknown;
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/items/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read one item */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The item. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Item"];
                    };
                };
                /** @description No item has that id. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description The refusal's kind, with its facts beside it. */
                            error: {
                                /** @enum {string} */
                                code: "no-such-item";
                            } & {
                                [key: string]: unknown;
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/items/{id}/archive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Archive an item
         * @description Hides the item from the queue. It stays in the feed and stays processable. Archiving one that is already archived is refused rather than absorbed: a second archive would overwrite the reason and time the first recorded.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["ArchiveRequest"];
                };
            };
            responses: {
                /** @description The item, now archived. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Item"];
                    };
                };
                /** @description The body could not be read as this request. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description The refusal's kind, with its facts beside it. */
                            error: {
                                /** @enum {string} */
                                code: "malformed-json" | "malformed-envelope";
                            } & {
                                [key: string]: unknown;
                            };
                        };
                    };
                };
                /** @description No item has that id. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description The refusal's kind, with its facts beside it. */
                            error: {
                                /** @enum {string} */
                                code: "no-such-item" | "item-purged";
                            } & {
                                [key: string]: unknown;
                            };
                        };
                    };
                };
                /** @description The item is already archived. */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description The refusal's kind, with its facts beside it. */
                            error: {
                                /** @enum {string} */
                                code: "already-archived" | "not-archived";
                            } & {
                                [key: string]: unknown;
                            };
                        };
                    };
                };
                /** @description The body was not JSON. */
                415: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description The refusal's kind, with its facts beside it. */
                            error: {
                                /** @enum {string} */
                                code: "unsupported-media-type";
                            } & {
                                [key: string]: unknown;
                            };
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/items/{id}/unarchive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Unarchive an item
         * @description Returns the item to the queue at its unchanged position, since archiving never moved it. Unarchiving one that is not archived is refused.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["UnarchiveRequest"];
                };
            };
            responses: {
                /** @description The item, no longer archived. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Item"];
                    };
                };
                /** @description The body could not be read as this request. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description The refusal's kind, with its facts beside it. */
                            error: {
                                /** @enum {string} */
                                code: "malformed-json" | "malformed-envelope";
                            } & {
                                [key: string]: unknown;
                            };
                        };
                    };
                };
                /** @description No item has that id. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description The refusal's kind, with its facts beside it. */
                            error: {
                                /** @enum {string} */
                                code: "no-such-item" | "item-purged";
                            } & {
                                [key: string]: unknown;
                            };
                        };
                    };
                };
                /** @description The item is not archived. */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description The refusal's kind, with its facts beside it. */
                            error: {
                                /** @enum {string} */
                                code: "already-archived" | "not-archived";
                            } & {
                                [key: string]: unknown;
                            };
                        };
                    };
                };
                /** @description The body was not JSON. */
                415: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description The refusal's kind, with its facts beside it. */
                            error: {
                                /** @enum {string} */
                                code: "unsupported-media-type";
                            } & {
                                [key: string]: unknown;
                            };
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/items/{id}/tag": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Tag an item
         * @description Adds one tag. Classification does not move an item, so a tagged item keeps its place in the queue. A tag the item already carries is absorbed rather than refused, keeping the attribution and time it has: a tag's name is the whole of the request, unlike an archive's reason.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["TagRequest"];
                };
            };
            responses: {
                /** @description The item, as it now stands. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Item"];
                    };
                };
                /** @description The body could not be read as this request. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description The refusal's kind, with its facts beside it. */
                            error: {
                                /** @enum {string} */
                                code: "malformed-json" | "malformed-envelope";
                            } & {
                                [key: string]: unknown;
                            };
                        };
                    };
                };
                /** @description No item has that id. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description The refusal's kind, with its facts beside it. */
                            error: {
                                /** @enum {string} */
                                code: "no-such-item" | "item-purged";
                            } & {
                                [key: string]: unknown;
                            };
                        };
                    };
                };
                /** @description A revision already supersedes the item; classify that instead. */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description The refusal's kind, with its facts beside it. */
                            error: {
                                /** @enum {string} */
                                code: "item-superseded";
                            } & {
                                [key: string]: unknown;
                            };
                        };
                    };
                };
                /** @description The body was not JSON. */
                415: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description The refusal's kind, with its facts beside it. */
                            error: {
                                /** @enum {string} */
                                code: "unsupported-media-type";
                            } & {
                                [key: string]: unknown;
                            };
                        };
                    };
                };
                /** @description The tag was declined. */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description The refusal's kind, with its facts beside it. */
                            error: {
                                /** @enum {string} */
                                code: "tag-invalid";
                            } & {
                                [key: string]: unknown;
                            };
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/items/{id}/untag": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Remove a tag from an item
         * @description Removes one tag. A tag the item does not carry is absorbed rather than refused, on the same terms as adding one it already has.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["TagRequest"];
                };
            };
            responses: {
                /** @description The item, as it now stands. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Item"];
                    };
                };
                /** @description The body could not be read as this request. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description The refusal's kind, with its facts beside it. */
                            error: {
                                /** @enum {string} */
                                code: "malformed-json" | "malformed-envelope";
                            } & {
                                [key: string]: unknown;
                            };
                        };
                    };
                };
                /** @description No item has that id. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description The refusal's kind, with its facts beside it. */
                            error: {
                                /** @enum {string} */
                                code: "no-such-item" | "item-purged";
                            } & {
                                [key: string]: unknown;
                            };
                        };
                    };
                };
                /** @description A revision already supersedes the item; classify that instead. */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description The refusal's kind, with its facts beside it. */
                            error: {
                                /** @enum {string} */
                                code: "item-superseded";
                            } & {
                                [key: string]: unknown;
                            };
                        };
                    };
                };
                /** @description The body was not JSON. */
                415: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description The refusal's kind, with its facts beside it. */
                            error: {
                                /** @enum {string} */
                                code: "unsupported-media-type";
                            } & {
                                [key: string]: unknown;
                            };
                        };
                    };
                };
                /** @description The tag was declined. */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description The refusal's kind, with its facts beside it. */
                            error: {
                                /** @enum {string} */
                                code: "tag-invalid";
                            } & {
                                [key: string]: unknown;
                            };
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/items/{id}/edit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Edit an item's content
         * @description Changes what the capture says. The pool decides the shape: an in-place **amendment** while the item is the newest in the feed and unprocessed, an appended **revision** otherwise. The client does not say which it wants and cannot know, so the outcome is read off the answer.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["EditRequest"];
                };
            };
            responses: {
                /** @description What the edit became: the amended item, or the revision and the item it supersedes. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["EditOutcome"];
                    };
                };
                /** @description The body could not be read as this request. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description The refusal's kind, with its facts beside it. */
                            error: {
                                /** @enum {string} */
                                code: "malformed-json" | "malformed-envelope";
                            } & {
                                [key: string]: unknown;
                            };
                        };
                    };
                };
                /** @description No item has that id. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description The refusal's kind, with its facts beside it. */
                            error: {
                                /** @enum {string} */
                                code: "no-such-item" | "item-purged";
                            } & {
                                [key: string]: unknown;
                            };
                        };
                    };
                };
                /** @description A revision already supersedes the item; edit that instead. */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description The refusal's kind, with its facts beside it. */
                            error: {
                                /** @enum {string} */
                                code: "item-superseded";
                            } & {
                                [key: string]: unknown;
                            };
                        };
                    };
                };
                /** @description The body was not JSON. */
                415: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description The refusal's kind, with its facts beside it. */
                            error: {
                                /** @enum {string} */
                                code: "unsupported-media-type";
                            } & {
                                [key: string]: unknown;
                            };
                        };
                    };
                };
                /** @description The payload was declined. */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description The refusal's kind, with its facts beside it. */
                            error: {
                                /** @enum {string} */
                                code: "payload-invalid" | "payload-type-changed" | "missing-asset-slot" | "unknown-asset";
                            } & {
                                [key: string]: unknown;
                            };
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/items/{id}/mark-processed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Mark an item processed by hand
         * @description The user carried the content onward themselves. This is routing whose destination is the user: it appends a routing record, takes the item out of the queue, and leaves it in the feed unarchived. Doing it twice appends two records and is not refused.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["MarkProcessedRequest"];
                };
            };
            responses: {
                /** @description The routing record that was appended. A record has no URL of its own, so there is nothing for a 201 to name. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RoutingRecord"];
                    };
                };
                /** @description The body could not be read as this request. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description The refusal's kind, with its facts beside it. */
                            error: {
                                /** @enum {string} */
                                code: "malformed-json" | "malformed-envelope";
                            } & {
                                [key: string]: unknown;
                            };
                        };
                    };
                };
                /** @description No item has that id. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description The refusal's kind, with its facts beside it. */
                            error: {
                                /** @enum {string} */
                                code: "no-such-item" | "item-purged";
                            } & {
                                [key: string]: unknown;
                            };
                        };
                    };
                };
                /** @description The body was not JSON. */
                415: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description The refusal's kind, with its facts beside it. */
                            error: {
                                /** @enum {string} */
                                code: "unsupported-media-type";
                            } & {
                                [key: string]: unknown;
                            };
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/items/{id}/routing": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read where an item has been
         * @description An item's routing records, oldest first. Not paginated: they are item state rather than a surface over the pool, and go when the item does.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The item's routing records. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RoutingRecords"];
                    };
                };
                /** @description No item has that id. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description The refusal's kind, with its facts beside it. */
                            error: {
                                /** @enum {string} */
                                code: "no-such-item";
                            } & {
                                [key: string]: unknown;
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/destinations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read the destinations the pool holds
         * @description A read of pool state: it answers at once, cannot fail, and probes nothing. Retired ones are listed, since a routing record may still name one. Not paginated: there are as many destinations as a person made. Which destinations exist is **not** stable for the life of a connection — a client re-reads rather than caching for the session.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Every destination the pool holds. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Destinations"];
                    };
                };
            };
        };
        put?: never;
        /**
         * Create a destination
         * @description From a name, a kind and that kind's settings. The id is minted and answered; a name is a label and need not be unique. Settings are validated against the kind's `settingsSchema` and a failure carries the schema issues.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateDestinationRequest"];
                };
            };
            responses: {
                /** @description Created. `Location` names the destination. */
                201: {
                    headers: {
                        Location: string;
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Destination"];
                    };
                };
                /** @description The body could not be read as this request. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description The refusal's kind, with its facts beside it. */
                            error: {
                                /** @enum {string} */
                                code: "malformed-json" | "malformed-envelope";
                            } & {
                                [key: string]: unknown;
                            };
                        };
                    };
                };
                /** @description The body was not JSON. */
                415: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description The refusal's kind, with its facts beside it. */
                            error: {
                                /** @enum {string} */
                                code: "unsupported-media-type";
                            } & {
                                [key: string]: unknown;
                            };
                        };
                    };
                };
                /** @description The kind is not one this daemon has, or the settings do not satisfy it. */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description The refusal's kind, with its facts beside it. */
                            error: {
                                /** @enum {string} */
                                code: "unknown-destination-kind" | "invalid-destination-settings";
                            } & {
                                [key: string]: unknown;
                            };
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/destination-kinds": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read the destination kinds this daemon has an adapter for
         * @description Each with the `settingsSchema` a destination of that kind must satisfy, which is what a client builds its form from. The same arrangement as a capability's `targetSchema`, one level up: the daemon publishes what a kind needs and holds no opinion about how it is asked for.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Every kind, with the schema its settings must satisfy. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DestinationKinds"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/destinations/{id}/description": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Ask one destination what it can do
         * @description Split from the list because they are different animals: what a destination *is* comes from the pool, and what it can *do* is I/O that may hang or fail. `described` carries the capabilities the adapter declared; `undescribable` went and looked and could not say; `unusable` could not be asked at all — no adapter speaks its kind, or its settings no longer satisfy that kind. `targetSchema` is JSON Schema and is the whole of what a client needs to build a `target`.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description What it answered. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DestinationDescription"];
                    };
                };
                /** @description No destination has that id. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description The refusal's kind, with its facts beside it. */
                            error: {
                                /** @enum {string} */
                                code: "unknown-destination";
                            } & {
                                [key: string]: unknown;
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/destinations/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete a destination no record has ever named
         * @description A typo need not become permanent furniture. Anything a routing record has ever named can never stop resolving, and is refused with `destination-in-use`, which names retirement as what to do instead.
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Gone. Nothing ever named it. */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description No destination has that id. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description The refusal's kind, with its facts beside it. */
                            error: {
                                /** @enum {string} */
                                code: "unknown-destination";
                            } & {
                                [key: string]: unknown;
                            };
                        };
                    };
                };
                /** @description A routing record names it. Retire it instead. */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description The refusal's kind, with its facts beside it. */
                            error: {
                                /** @enum {string} */
                                code: "destination-in-use";
                            } & {
                                [key: string]: unknown;
                            };
                        };
                    };
                };
            };
        };
        options?: never;
        head?: never;
        /**
         * Change a destination's name or settings
         * @description The kind is fixed: changing it would make one destination two, and a record cannot tell which it meant. Renaming is free, because a record names the id. Last write wins.
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateDestinationRequest"];
                };
            };
            responses: {
                /** @description The destination as it now stands. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Destination"];
                    };
                };
                /** @description The body could not be read as this request. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description The refusal's kind, with its facts beside it. */
                            error: {
                                /** @enum {string} */
                                code: "malformed-json" | "malformed-envelope";
                            } & {
                                [key: string]: unknown;
                            };
                        };
                    };
                };
                /** @description No destination has that id. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description The refusal's kind, with its facts beside it. */
                            error: {
                                /** @enum {string} */
                                code: "unknown-destination";
                            } & {
                                [key: string]: unknown;
                            };
                        };
                    };
                };
                /** @description The body was not JSON. */
                415: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description The refusal's kind, with its facts beside it. */
                            error: {
                                /** @enum {string} */
                                code: "unsupported-media-type";
                            } & {
                                [key: string]: unknown;
                            };
                        };
                    };
                };
                /** @description The settings do not satisfy the kind's schema. Nothing was written. */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description The refusal's kind, with its facts beside it. */
                            error: {
                                /** @enum {string} */
                                code: "unknown-destination-kind" | "invalid-destination-settings";
                            } & {
                                [key: string]: unknown;
                            };
                        };
                    };
                };
            };
        };
        trace?: never;
    };
    "/v1/destinations/{id}/retire": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Stop offering a destination for new routing
         * @description Reversible, and nothing already decided is disturbed: records keep resolving and a pending delivery still lands. Retiring one that is already retired is refused rather than absorbed, since a second would overwrite the instant the first recorded.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The destination, now retired. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Destination"];
                    };
                };
                /** @description No destination has that id. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description The refusal's kind, with its facts beside it. */
                            error: {
                                /** @enum {string} */
                                code: "unknown-destination";
                            } & {
                                [key: string]: unknown;
                            };
                        };
                    };
                };
                /** @description It is already retired. */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description The refusal's kind, with its facts beside it. */
                            error: {
                                /** @enum {string} */
                                code: "already-retired" | "not-retired";
                            } & {
                                [key: string]: unknown;
                            };
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/destinations/{id}/unretire": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Offer a retired destination again */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The destination, offered again. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Destination"];
                    };
                };
                /** @description No destination has that id. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description The refusal's kind, with its facts beside it. */
                            error: {
                                /** @enum {string} */
                                code: "unknown-destination";
                            } & {
                                [key: string]: unknown;
                            };
                        };
                    };
                };
                /** @description It is not retired. */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description The refusal's kind, with its facts beside it. */
                            error: {
                                /** @enum {string} */
                                code: "already-retired" | "not-retired";
                            } & {
                                [key: string]: unknown;
                            };
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/items/{id}/route": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Route an item to a destination
         * @description Records the decision and attempts the delivery once, inline. **The record answered may name a delivery that has not happened**: `state` is `pending` when the destination could not be reached, and a job carries it out later. A destination that was reached and refused writes nothing.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RouteRequest"];
                };
            };
            responses: {
                /** @description The routing record. Read `state` rather than reading a record as arrival. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RoutingRecord"];
                    };
                };
                /** @description The body could not be read as this request. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description The refusal's kind, with its facts beside it. */
                            error: {
                                /** @enum {string} */
                                code: "malformed-json" | "malformed-envelope";
                            } & {
                                [key: string]: unknown;
                            };
                        };
                    };
                };
                /** @description No item has that id. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description The refusal's kind, with its facts beside it. */
                            error: {
                                /** @enum {string} */
                                code: "no-such-item" | "item-purged";
                            } & {
                                [key: string]: unknown;
                            };
                        };
                    };
                };
                /** @description The destination is retired, or the running code cannot make sense of it. Nothing was written. */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description The refusal's kind, with its facts beside it. */
                            error: {
                                /** @enum {string} */
                                code: "destination-retired" | "destination-unusable";
                            } & {
                                [key: string]: unknown;
                            };
                        };
                    };
                };
                /** @description The body was not JSON. */
                415: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description The refusal's kind, with its facts beside it. */
                            error: {
                                /** @enum {string} */
                                code: "unsupported-media-type";
                            } & {
                                [key: string]: unknown;
                            };
                        };
                    };
                };
                /** @description The destination, the capability, the payload type or the target was declined. Nothing was written. */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description The refusal's kind, with its facts beside it. */
                            error: {
                                /** @enum {string} */
                                code: "unknown-destination" | "capability-undeclared" | "payload-type-unsupported" | "target-invalid" | "rejected-by-destination" | "delivery-outcome-unknown" | "unreachable";
                            } & {
                                [key: string]: unknown;
                            };
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/routing/{record}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cancel a pending delivery
         * @description Removes a reservation whose delivery has not landed, which returns the item to the queue at its unchanged content time. Routing it again is what a retry by hand is, so there is no route for one.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    record: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Called off. The item is back in the queue. */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description No record has that id. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description The refusal's kind, with its facts beside it. */
                            error: {
                                /** @enum {string} */
                                code: "no-such-record";
                            } & {
                                [key: string]: unknown;
                            };
                        };
                    };
                };
                /** @description The record has already delivered, or a host is holding a lease on it. */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description The refusal's kind, with its facts beside it. */
                            error: {
                                /** @enum {string} */
                                code: "not-pending" | "delivery-in-flight";
                            } & {
                                [key: string]: unknown;
                            };
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/actions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read the action log
         * @description Every action that changed state, newest first by default. Narrow it to one subject with `item`; the log outlives the material, so a purged item's entries are still answered.
         */
        get: {
            parameters: {
                query?: {
                    /** @description `newest-first` (default) or `oldest-first`. */
                    order?: string;
                    /** @description 1–500. Defaults to 50. A larger value is refused, not clamped. */
                    limit?: string;
                    /** @description The position to continue from: `<at>,<id>`, or a bare instant as a coarse entry point. */
                    after?: string;
                    /** @description Narrows the read to one subject. Never validated: an id no item has answers an empty page, since the log outlives what it describes. */
                    item?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description A page of the log. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ActionSlice"];
                    };
                };
                /** @description A parameter was understood and refused. */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description The refusal's kind, with its facts beside it. */
                            error: {
                                /** @enum {string} */
                                code: "limit-too-large" | "bad-limit" | "bad-order" | "bad-position";
                            } & {
                                [key: string]: unknown;
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/assets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload bytes
         * @description The body is the bytes, raw — not `multipart/form-data`. `Content-Type` is the asset's media type and is served back verbatim; `Content-Disposition` carries the filename, which is stored exactly as given. Anything may be uploaded; what may be rendered in place is decided on the way out.
         */
        post: {
            parameters: {
                query?: never;
                header: {
                    /** @description `attachment; filename="photo.png"`, or `filename*=UTF-8''…`. */
                    "content-disposition": string;
                    /** @description RFC 9530. Recomputed over the bytes received and refused on mismatch. Only `sha-256` is understood; any other algorithm is ignored. */
                    "repr-digest"?: string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "*/*": string;
                };
            };
            responses: {
                /** @description Stored. `Location` names the asset. */
                201: {
                    headers: {
                        Location: string;
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Asset"];
                    };
                };
                /** @description The body was larger than the configured limit. Nothing was stored. */
                413: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description The refusal's kind, with its facts beside it. */
                            error: {
                                /** @enum {string} */
                                code: "asset-too-large";
                            } & {
                                [key: string]: unknown;
                            };
                        };
                    };
                };
                /** @description The request carried no media type. */
                415: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description The refusal's kind, with its facts beside it. */
                            error: {
                                /** @enum {string} */
                                code: "unsupported-media-type";
                            } & {
                                [key: string]: unknown;
                            };
                        };
                    };
                };
                /** @description The upload was understood and declined. Nothing was stored. */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description The refusal's kind, with its facts beside it. */
                            error: {
                                /** @enum {string} */
                                code: "missing-filename" | "bad-digest" | "digest-mismatch";
                            } & {
                                [key: string]: unknown;
                            };
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/assets/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read one asset */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The asset. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Asset"];
                    };
                };
                /** @description No asset has that id. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description The refusal's kind, with its facts beside it. */
                            error: {
                                /** @enum {string} */
                                code: "no-such-asset" | "blob-missing";
                            } & {
                                [key: string]: unknown;
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/assets/{id}/content": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read an asset's bytes
         * @description The recorded media type, served honestly, with `nosniff` and a sandbox CSP. `Content-Disposition` is `inline` for media that cannot execute and `attachment` for everything else. `ETag` is the blob hash, and the response is immutable: an asset id names one blob forever.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The bytes. */
                200: {
                    headers: {
                        ETag: string;
                        "Content-Disposition": string;
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": string;
                    };
                };
                /** @description No asset has that id, or its blob is gone from disk. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description The refusal's kind, with its facts beside it. */
                            error: {
                                /** @enum {string} */
                                code: "no-such-asset" | "blob-missing";
                            } & {
                                [key: string]: unknown;
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CaptureOutcome: {
            /** @enum {string} */
            kind: "captured";
            item: components["schemas"]["Item"];
        } | {
            /** @enum {string} */
            kind: "already-captured";
            item: components["schemas"]["Item"];
            /** @enum {string} */
            matchedOn: "id" | "source";
        };
        Item: {
            id: string;
            source: string;
            sourceItemId: string;
            payload: {
                type: string;
                content: {
                    [key: string]: unknown;
                };
                metadata: {
                    [key: string]: unknown;
                };
                assets: {
                    slot: string;
                    asset: string;
                }[];
            };
            tags: {
                name: string;
                by: {
                    /** @enum {string} */
                    kind: "person";
                } | {
                    /** @enum {string} */
                    kind: "provider";
                    provider: string;
                } | {
                    /** @enum {string} */
                    kind: "source";
                    source: string;
                };
                addedAt: string;
            }[];
            createdAt: string;
            contentUpdatedAt?: string;
            revisionOf?: string;
            archived?: {
                archivedAt: string;
                reason?: string;
            };
            modifiedAt: string;
            supersededBy?: string;
        };
        CaptureEnvelope: {
            id?: string;
            source: string;
            sourceItemId: string;
            /**
             * @description An ISO 8601 instant: a date-time carrying an offset (`2026-08-08T09:00:00Z`, `2026-08-08T09:00:00+02:00`), or a date alone, which means midnight UTC. A date-time without an offset is refused — there is no way to tell which zone it was written in.
             * @example 2026-08-08T09:00:00.000Z
             */
            capturedAt: string;
            payload: {
                type: string;
                content: {
                    [key: string]: unknown;
                };
                metadata: {
                    [key: string]: unknown;
                };
                assets: {
                    slot: string;
                    asset: string;
                }[];
            };
            tags?: string[];
        };
        ItemSlice: {
            values: components["schemas"]["Item"][];
            /**
             * @description A ready-to-fetch relative URL for the next page. Absent on the last page.
             * @example /v1/feed?order=newest-first&limit=50&after=...
             */
            next?: string;
        };
        ArchiveRequest: {
            reason?: string;
        };
        UnarchiveRequest: Record<string, never>;
        TagRequest: {
            tag: string;
        };
        EditOutcome: {
            /** @enum {string} */
            kind: "amended";
            item: components["schemas"]["Item"];
        } | {
            /** @enum {string} */
            kind: "revised";
            revision: components["schemas"]["Item"];
            supersedes: string;
        };
        EditRequest: {
            type: string;
            content: {
                [key: string]: unknown;
            };
            metadata: {
                [key: string]: unknown;
            };
            assets: {
                slot: string;
                asset: string;
            }[];
        };
        RoutingRecord: {
            id: string;
            item: string;
            target: {
                /** @enum {string} */
                kind: "destination";
                destination: string;
                capability: string;
                target: {
                    [key: string]: unknown;
                };
            } | {
                /** @enum {string} */
                kind: "user";
                note?: string;
            };
            /** @enum {string} */
            state: "pending" | "delivered";
            at: string;
            pointer?: string;
        };
        MarkProcessedRequest: {
            /**
             * @description Where the user carried the content, in their own words.
             * @example pasted into the fiction-a vault
             */
            note?: string;
        };
        RoutingRecords: {
            values: components["schemas"]["RoutingRecord"][];
        };
        Destinations: {
            values: components["schemas"]["Destination"][];
        };
        Destination: {
            id: string;
            name: string;
            kind: string;
            settings: {
                [key: string]: unknown;
            };
            retired: boolean;
        };
        CreateDestinationRequest: {
            /**
             * @description What a person calls it. Changeable, and need not be unique.
             * @example Vault
             */
            name: string;
            /**
             * @description One of the names `GET /v1/destination-kinds` reports.
             * @example filesystem
             */
            kind: string;
            /**
             * @description Must satisfy that kind's `settingsSchema`.
             * @example {
             *       "root": "~/notes",
             *       "accepts": [
             *         "text",
             *         "image"
             *       ]
             *     }
             */
            settings: {
                [key: string]: unknown;
            };
        };
        DestinationKinds: {
            values: components["schemas"]["DestinationKind"][];
        };
        DestinationKind: {
            name: string;
            settingsSchema: {
                [key: string]: unknown;
            };
        };
        DestinationDescription: {
            /** @enum {string} */
            kind: "described";
            capabilities: components["schemas"]["Capability"][];
        } | {
            /** @enum {string} */
            kind: "undescribable";
            detail: string;
        } | {
            /** @enum {string} */
            kind: "unusable";
            detail: string;
        };
        Capability: {
            name: string;
            accepts: string[];
            targetSchema: {
                [key: string]: unknown;
            };
        };
        UpdateDestinationRequest: {
            name?: string;
            settings?: {
                [key: string]: unknown;
            };
        };
        RouteRequest: {
            /**
             * @description One of the ids `GET /v1/destinations` reports.
             * @example 019a3f2c-0e6e-7c31-9f3a-6b1f2d5c4a77
             */
            destination: string;
            /**
             * @description One the destination declared. Anything else is refused.
             * @example create-file
             */
            capability: string;
            /**
             * @description What the capability is pointed at, in its own terms. Must satisfy the capability's `targetSchema`.
             * @example {
             *       "directory": "inbox",
             *       "filename": "a-thought.md"
             *     }
             */
            target: {
                [key: string]: unknown;
            };
        };
        ActionSlice: {
            values: components["schemas"]["Action"][];
            /**
             * @description A ready-to-fetch relative URL for the next page, carrying the filter. Absent on the last page.
             * @example /v1/actions?order=newest-first&limit=50&after=...
             */
            next?: string;
        };
        Action: {
            kind: string;
            id: string;
            subject?: string;
            by: {
                /** @enum {string} */
                kind: "notemap";
            } | {
                /** @enum {string} */
                kind: "person";
            } | {
                /** @enum {string} */
                kind: "provider";
                provider: string;
            } | {
                /** @enum {string} */
                kind: "source";
                source: string;
            };
            /** @description When the pool applied the action, which for a capture is its arrival. */
            at: string;
            /** @description Facts about what changed, shaped by the kind. */
            detail: {
                [key: string]: unknown;
            };
        };
        Asset: {
            id: string;
            filename: string;
            mime: string;
            blob: string;
            bytes: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
